[client]
showErrorDetails = false

[theme]

# Primary accent for interactive elements
primaryColor = '#1976d2'  # Dark blue accent

# Background color for the main content area
backgroundColor = '#121212'  # Dark background

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1e1e1e'  # Darker background

# Color used for almost all text
textColor = '#FFFFFF'  # White text color

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"